# ===============================================
# MySQL Datasource Configuration
# ===============================================
# - Replace 'carshowcase_db' with your database name
# - Replace '<your-mysql-username>' and '<your-mysql-password>'
# ===============================================
# Make sure the port (3306) and database name (car_showcase_db) are correct
spring.datasource.url=your-datasource-url

# Make sure these are the correct credentials for your MySQL server
spring.datasource.username=your-username
spring.datasource.password=your-password

#spring.datasource.url=jdbc:mysql://localhost:3306/car_showcase_db
#
## Make sure these are the correct credentials for your MySQL server
#spring.datasource.username=root
#spring.datasource.password=Raj2006@#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# These lines are also good to have


# ===============================================
# JPA/Hibernate Configuration
# ===============================================
# Use the MySQL-specific dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 'update' will modify the database schema to match your entities on startup.
# 'validate' is safer for production.
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=jwt-secret
app.jwt.expiration-ms = 86400000
 # 24 hours

config.cloudinary.cloud.secret:your-cloudinary-secret
config.cloudinary.cloud.key:your-cloudinary-key
config.cloudinary.cloud.name:you-cloudinary-name

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
